# scrub.py - Wipe VDB and all generated JSON files
# FOR TESTING PURPOSES ONLY!

import shutil
import sqlite3
from pathlib import Path

print("=" * 60)
print("🧹 SCRUB - Wipe VDB and all generated JSON files")
print("=" * 60)
print()
print("⚠️  WARNING: This will delete ALL data generated by the pipeline!")
print("⚠️  This includes VDB, all JSON files, and processed data.")
print()
confirm = input("Type 'YES' to confirm deletion: ")

if confirm != "YES":
    print("❌ Cancelled.")
    exit()

print("\n🧹 Scrubbing...\n")

# 1. Delete VDB (LanceDB)
vdb_path = Path("vectordb")
if vdb_path.exists():
    shutil.rmtree(vdb_path)
    print(f"   ✅ Deleted VDB: {vdb_path}")

# 2. Delete SQLite database
db_path = Path("data/pipeline.db")
if db_path.exists():
    db_path.unlink()
    print(f"   ✅ Deleted SQLite: {db_path}")

# 3. Delete JSON files in each stage folder
stages = ["02normalise", "03segment", "04names", "06images", "07keys", "08commentary", "09audio", "10generate", "11translate"]

for stage in stages:
    stage_path = Path(stage)
    if stage_path.exists():
        json_files = list(stage_path.glob("*.json"))
        for f in json_files:
            f.unlink()
        # Also delete subfolders in 02normalise and 03segment
        if stage in ["02normalise", "03segment"]:
            for subdir in stage_path.iterdir():
                if subdir.is_dir():
                    shutil.rmtree(subdir)
                    print(f"   ✅ Deleted folder: {subdir}")
        if json_files:
            print(f"   ✅ Deleted {len(json_files)} JSON files from {stage}/")

# 4. Delete manga generated data
manga_paths = [
    "manga/panels",
    "manga/segmented", 
    "data/raw/manga/panels",
    "data/generated/embeddings"
]

for mp in manga_paths:
    p = Path(mp)
    if p.exists():
        shutil.rmtree(p)
        print(f"   ✅ Deleted manga data: {mp}")

# 5. Delete audio clips
audio_clips = Path("data/audio_clips")
if audio_clips.exists():
    shutil.rmtree(audio_clips)
    print(f"   ✅ Deleted audio clips")

# 6. Delete export folder
exports = Path("12rebuild/exports")
if exports.exists():
    shutil.rmtree(exports)
    print(f"   ✅ Deleted exports")

print("\n" + "=" * 60)
print("✅ SCRUB COMPLETE! Everything has been wiped.")
print("=" * 60)
print()
print("📋 To start fresh, run the pipeline in order:")
print("   1. python 01ingest/01ingest.py --url <URL> --slug <slug>")
print("   2. python 02normalise/02normalise.py --slug <slug>")
print("   3. python 03segment/03segment.py --slug <slug>")
print("   4. python 04names/04names.py")
print("   5. python 07keys/07keys_vdb.py")
print("   6. python 08commentary/08commentary_vdb.py")
print("   7. python 10generate/10generate.py")
print("   8. python 11translate/11translate.py")
print("   9. python 12rebuild/12rebuild.py")
